import localFont from "next/font/local";
import "./globals.css";
import { Montserrat } from "next/font/google";
import StoreProvider from "./StoreProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <StoreProvider>
          <div className="flex flex-col  h-[100dvh] w-full max-w-lg mx-auto overflow-y-auto overflow-x-hidden relative justify-between">
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
